services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.api.dev
    entrypoint: ["./entrypoint.dev.sh"]
    ports:
      - 8887:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15.8
    env_file: .env.db.dev
    volumes:
      - llmpgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  llmpgdata:
